-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

module Main where

problem2 a b n 
	| b >= n = 0							-- We have reached our limit
	| even b = (b + ( problem2 b (a+b) n))  -- This is an even term
	| otherwise = problem2 b (a+b) n 		-- Just keep going in the sequence

main = do print (problem2 1 2 4000000)
